mctpd: Handle SIGTERM to enable test coverage reports
`PATH=$PWD/venv/bin/:$PATH meson setup -Db_coverage=true build` yields a
build that passes `meson test -C build` yet cannot successfully generate
a test coverage report:

```
$ meson test -C build
ninja: Entering directory `./build'
[21/21] Linking target test-mctpd
1/1 test-mctpd        OK              0.28s   1 subtests passed

Ok:                 1
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to ./build/meson-logs/testlog.txt
```

```
$ ninja -C build coverage-html
ninja: Entering directory `build'
[1/1] Generates HTML coverage report
FAILED: meson-internal__coverage-html
/home/andrew/.local/bin/meson --internal coverage --html . ./subprojects ./build ./build/meson-logs
Debian LLVM version 14.0.6
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: goldmont
genhtml: LCOV version 1.16
...
Scanning ./build for .gcda files ...
geninfo: WARNING: no .gcda files found in ./build - skipping!
Finished .info-file creation
lcov: ERROR: no valid records found in tracefile ./build/meson-logs/coverage.info.run
Combining tracefiles.
Reading tracefile ./build/meson-logs/coverage.info.initial
Reading tracefile ./build/meson-logs/coverage.info.run
Traceback (most recent call last):
  File "/home/andrew/.local/bin/meson", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 282, in run
    return run_script_command(args[1], args[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 223, in run_script_command
    return module.run(script_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mesonbuild/scripts/coverage.py", line 205, in run
    return coverage(options.outputs, options.source_root,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mesonbuild/scripts/coverage.py", line 132, in coverage
    subprocess.check_call([lcov_exe,
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lcov', '-a', './build/meson-logs/coverage.info.initial', '-a', './build/meson-logs/coverage.info.run', '--rc', 'lcov_branch_coverage=1', '-o', './build/meson-logs/coverage.info.raw']' returned non-zero exit status 255.
ninja: build stopped: subcommand failed.
```

The insightful observation here was that running `./build/test-mctpd`
*did* generate `.gcda` files as expected, event if the invocation
terminated early before doing anything interesting (due to the lack of
`MCTP_TEST_SOCK`).

`strace`ing out `meson test -C build` confirmed no gcda files were
written, and demonstrated that exit of test-mctpd was triggered from
pytest with `kill -SIGTERM ...`.

Add a SIGTERM handler such that we return from `sd_event_loop()` on
SIGTERM, yielding a graceful process exit by returning from main(),
which in-turns writes out the gcda files required for coverage
reporting.

Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>