mctp-bench: Adjust headers
bits/time.h is not be included directly, instead use time.h
since poll.h is included there is no need to include sys/poll.h

Fixes
../git/src/mctp-bench.c:2:10: fatal error: 'bits/time.h' file not found
    2 | #include <bits/time.h>
      |          ^~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>