tests: include string.h for memcpy
clang in the openembedded CI reports a build error:

    ../git/tests/mctp-ops-test.c:67:2: error: call to undeclared library function 'memcpy' with type 'void *(void *, const void *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       67 |         memcpy(&sd, CMSG_DATA(cmsg), sizeof(int));
          |         ^
    ../git/tests/mctp-ops-test.c:67:2: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
    1 error generated.

Add the required header.

Fixes: 0bac17d ("tests: introduce MCTP infrastructure test facility")
Reported-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>