tests: update to trio 0.31.0
The version of anyio that currently gets pulled in through asyncdbus
is incompatible with trio:

      File "/home/jk/devel/mctp/mctp/venv/lib/python3.11/site-packages/anyio/_backends/_trio.py", line 141, in cancel
        self.__original.cancel(reason)
      File "/home/jk/devel/mctp/mctp/venv/lib/python3.11/site-packages/trio/_core/_ki.py", line 183, in wrapper
        return fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
    TypeError: CancelScope.cancel() takes 1 positional argument but 2 were given

With the breaking change at
https://github.com/agronholm/anyio/commit/b2c933cd .

Bump trio to 0.31 to support cancel reasons.

Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>