mctp-ops: Include mctp.h for AF_MCTP definition
We're currently failing on musl with:

    [3/4] Compiling C object mctp.p/src_mctp-ops.c.o
    FAILED: mctp.p/src_mctp-ops.c.o
    x86_64-linux-musl-gcc -Imctp.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O0 -g -Wno-unused-parameter -MD -MQ mctp.p/src_mctp-ops.c.o -MF mctp.p/src_mctp-ops.c.o.d -o mctp.p/src_mctp-ops.c.o -c ../src/mctp-ops.c
    ../src/mctp-ops.c: In function ‘mctp_op_mctp_socket’:
    ../src/mctp-ops.c:18:23: error: ‘AF_MCTP’ undeclared (first use in this function)
       18 |         return socket(AF_MCTP, SOCK_DGRAM, 0);
          |                       ^~~~~~~
    ../src/mctp-ops.c:18:23: note: each undeclared identifier is reported only once for each function it appears in
    ../src/mctp-ops.c:19:1: warning: control reaches end of non-void function [-Wreturn-type]
       19 | }
          | ^

We need mctp.h for either linux/socket.h, or the fallback definitions.

Reported-by: Chanh Nguyen <chanh@os.amperecomputing.com>
Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>